### ISSUE TITLE
am I using this right?

### ISSUE THREAD

**Issue by tmpvar** [mikolalysenko/robust-compare#1]
``` javascript

var cmp = require('robust-compare');
var sum = require('two-sum');

console.log(cmp(sum(0.1, 0.2), sum(0.0, 0.3)));
// outputs: 2.7755575615628914e-17
```

I would expect the result of `cmp` to be `0`.  What am I missing?

**Comment by mikolalysenko** [comment]
This result is expected, since the literal double precision numbers 0.1 and 0.2 do not sum to 0.3 even in exact arithmetic.

**Comment by mikolalysenko** [comment]
On the other hand the _real_ numbers 0.1 and 0.2 would sum to 0.3

**Comment by tmpvar** [comment]
ok, that invalidates my entire mental model about `robust-*` - which explains why I found previous experimental results so confusing.

I'm hung up on how `exact` in this sense can mean `not exact` and would prefer not to guess.  Can you point me in the right direction to understand what is going on here? 

I've read https://github.com/mikolalysenko/robust-arithmetic-notes a few times and read Shewchuk's lecture notes, but my takeaway (I likely missed something) was the faulty mental model that led me here.

**Comment by mikolalysenko** [comment]
Ah, I can see how this would be a bit confusing.  So the problem here is how the floating point numbers are displayed.  0.1 is not really the real number 1/10.  It is actually a double precision number, which means that it some finite integer multiplied by a power of 2.  

Writing them out in binary, we see that:

```
double(0.1) = 0.00011001100110011001100110011001100110011001100110011010
double(0.2) = 0.00110011001100110011001100110011001100110011001100110100
double(0.3) = 0.01001100110011001100110011001100110011001100110011001100
```

So if we add double(0.1) to double(0.2) we get:

```
  0.00011001100110011001100110011001100110011001100110011010
+ 0.00110011001100110011001100110011001100110011001100110100
-------------------------------------------------------------------------
  0.01001100110011001100110011001100110011001100110011001110
```

Not:

```
0.01001100110011001100110011001100110011001100110011001100
```

The difference between the two numbers is:

```
0.00000000000000000000000000000000000000000000000000000010
```

Or written as a double, 

```
2.7755575615628914e-17
```

**Comment by mikolalysenko** [comment]
The exact arithmetic libraries perform exact computations on double precision numbers, not on their displayed values.  The real issue here is not in robust compare, but rather in how double precision numbers are printed for display purposes.

**Comment by tmpvar** [comment]
thank you for taking the time to explain this, my apologies for adding noise to `robust-compare` but this behavior has been an open question to me for a while (and actually a non-starter for my use of `robust-*`)

I have been operating under the assumption that non-overlapping sequences were a way of encoding floating point imprecision like the one seen above.  Which lead me to believe that 

`[0.0, 0.1] + [0.0, 0.2]` should result in something like `[-0.00000000000000004, 0.30000000000000004]`

which I suppose is nearly the case, as `0.30000000000000004 - 2.7755575615628914e-17 * 2 = 0.3` although I'm pretty sure that behavior cannot be trusted.

The benefit of using `robust-*` is still a bit unclear seeing that numerical issues are propagated through operations similar to normal FP arithmetic.  Perhaps another read through Shewchuk's paper would help clarify or if you have any further thoughts, I'm all ears!
